# Generated by Django 2.1.7 on 2022-04-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslotbook',
            old_name='customer_id',
            new_name='client_id',
        ),
    ]
