# Generated by Django 2.1.7 on 2022-04-16 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20220415_0025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0002_auto_20220416_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotCancel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id_cancel', to=settings.AUTH_USER_MODEL)),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manger_id_cancel', to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Rooms')),
            ],
        ),
    ]
