# Generated by Django 2.1.7 on 2022-04-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_timeslotcancel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslotcancel',
            old_name='customer_id',
            new_name='client_id',
        ),
    ]
