# Generated by Django 4.0.4 on 2022-04-14 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_first_name_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number in format +919999999999. Upto 10 digits', regex='\\+?1?\\d{9,10}$')]),
        ),
    ]
